# This rule is not used by the project mcp-server-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over mcpserver.opendatahub.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: mcp-server-operator
    app.kubernetes.io/managed-by: kustomize
  name: mcpserver-admin-role
rules:
- apiGroups:
  - mcpserver.opendatahub.io
  resources:
  - mcpservers
  verbs:
  - '*'
- apiGroups:
  - mcpserver.opendatahub.io
  resources:
  - mcpservers/status
  verbs:
  - get
